EvaluationSystem/Models/GradingPlanViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Models
{
    public class GradingPlanViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Tên tiêu đề")]
        [Required(ErrorMessage = "Tên tiêu đề kế hoạch")]
        public string Titel { get; set; }
        [Display(Name = "Ghi chú")]
        public string Note { get; set; }
        [Required(ErrorMessage = "Ngày bắt đầu")]
        [Display(Name = "Ngày bắt đầu")]
        public DateTime? StartDate { get; set; }
        [Required(ErrorMessage = "Ngày kết thúc")]
        [Display(Name = "Ngày kết thúc")]
        public DateTime? EndDate { get; set; }
        public DateTime? CreatedDate { get; set; }

        public DateTime? ModifiedDate { get; set; }

    }
}

EvaluationSystem/Controllers/GradingPlanController.cs
using EvaluationSystem.Data.Entities;
using EvaluationSystem.Data.Interfaces;
using EvaluationSystem.Data.Repositories;
using EvaluationSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Controllers
{
    public class GradingPlanController : Controller
    {
        IGradingPlanRepository _gradingPlanRepository;

        public GradingPlanController(IGradingPlanRepository gradingPlanRepository)
        {
            _gradingPlanRepository = gradingPlanRepository;
        }
        // GET: Student
        public ActionResult Index()
        {
            var gradingPlanListDb = _gradingPlanRepository.ListAllInfo();
            var models = gradingPlanListDb.Select(x => new GradingPlanViewModel
            {
                Id = x.Id,
                Titel = x.Titel,
                Note = x.Note,
                StartDate = x.StartDate,
                EndDate = x.EndDate,
                CreatedDate = x.CreatedDate,
                ModifiedDate = x.ModifiedDate,
            });
            return View(models);
        }
        public ActionResult Details(int Id)
        {
            var gradingPlan = _gradingPlanRepository.GetInfoById(Id);
            var model = new GradingPlanViewModel();
            if (gradingPlan != null)
            {
                model.Id = Id;
                model.Titel = gradingPlan.Titel;
                model.Note = gradingPlan.Note;
                model.StartDate = gradingPlan.StartDate;
                model.EndDate = gradingPlan.EndDate;
                model.CreatedDate = gradingPlan.CreatedDate;
                model.ModifiedDate = gradingPlan.ModifiedDate;
                return View(model);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Create()
        {
            GradingPlanViewModel model = new GradingPlanViewModel();
            return View(model);
        }
       
        [HttpPost]
        public ActionResult Create(GradingPlanViewModel models)
        {
            if (ModelState.IsValid)
            {
                GradingPlan gradingPlan = new GradingPlan();
                gradingPlan.Titel = models.Titel;
                gradingPlan.Note = models.Note;
                gradingPlan.StartDate = models.StartDate;
                gradingPlan.EndDate = models.EndDate;
                gradingPlan.CreatedDate = DateTime.Now;
                _gradingPlanRepository.Add(gradingPlan);
                if (gradingPlan.Id > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(models);
        }
        public ActionResult Edit(int Id)
        {
            var gradingPlan = _gradingPlanRepository.GetById(Id);
            GradingPlanViewModel model = new GradingPlanViewModel();
            if (gradingPlan != null)
            {
                model.Titel = gradingPlan.Titel;
                model.Note = gradingPlan.Note;
                model.StartDate = gradingPlan.StartDate;
                model.EndDate = gradingPlan.EndDate;
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(GradingPlanViewModel model)
        {
            if (ModelState.IsValid)
            {
                var gradingPlan = _gradingPlanRepository.GetById(model.Id);
                if (gradingPlan != null)
                {
                    gradingPlan.Titel = model.Titel;
                    gradingPlan.Note = model.Note;
                    gradingPlan.StartDate = model.StartDate;
                    gradingPlan.EndDate = model.EndDate;
                    gradingPlan.ModifiedDate = DateTime.Now;
                    _gradingPlanRepository.Update(gradingPlan);
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
            
        public ActionResult Delete(int Id)
        {
            var gradingPlan = _gradingPlanRepository.GetById(Id);
            if (gradingPlan != null)
            {
                _gradingPlanRepository.Delete(Id);

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

EvaluationSystem/Views/GradingPlan/Create.cshtml
@model GradingPlanViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

    <!-- Basic Layout & Basic with Icons -->
    <div class="row">
        <!-- Basic Layout -->
        <div class="col-xxl">
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Trang thêm kế hoạch chấm điểm</h5>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Create", "GradingPlan", FormMethod.Post))
                    {
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.Titel, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Titel, new { @class = "form-control", style = "" })
                                @Html.ValidationMessageFor(x => x.Titel, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.Note, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Note, new { @class = "form-control", style = "" })
                                @Html.ValidationMessageFor(x => x.Note, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.StartDate, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control", type = "date" })
                                @Html.ValidationMessageFor(x => x.StartDate, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.EndDate, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control", type = "date" })
                                @Html.ValidationMessageFor(x => x.EndDate, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Lưu</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- / Content -->
<!-- Footer -->

EvaluationSystem/Views/GradingPlan/Edit.cshtml
@model GradingPlanViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

    <!-- Basic Layout & Basic with Icons -->
    <div class="row">
        <!-- Basic Layout -->
        <div class="col-xxl">
            <div class="card mb-4">
                <div class="card-header d-flex align-items-center justify-content-between">
                    <h5 class="mb-0">Chỉnh sửa khoa</h5>
                </div>
                <div class="card-body">
                    @using (Html.BeginForm("Edit", "GradingPlan", FormMethod.Post))
                    {
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.Titel, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Titel, new { @class = "form-control", style = "" })
                                @Html.ValidationMessageFor(x => x.Titel, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.Note, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.Note, new { @class = "form-control", style = "" })
                                @Html.ValidationMessageFor(x => x.Note, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.StartDate, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control", style = "", type = "date" })
                                @Html.ValidationMessageFor(x => x.StartDate, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row mb-3">
                            @Html.LabelFor(x => x.EndDate, new { @class = "col-sm-2 col-form-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control", style = "", type = "date" })
                                @Html.ValidationMessageFor(x => x.EndDate, null, new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-primary">Cập nhật</button>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<!-- / Content -->
<!-- Footer -->

EvaluationSystem/Views/GradingPlan/Index.cshtml
@model IEnumerable<GradingPlanViewModel>
@using EvaluationSystem.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 0;
}
<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Basic Tables</h4>

<!-- Basic Bootstrap Table -->
<div class="card">
    <h5 class="card-header">Danh dách kế hoạch chấm điểm</h5>
    <div class="table-responsive text-nowrap">
        <table class="table">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Tiêu đề</th>
                    <th>Ghi chú</th>
                    <th>Ngày bắt đầu</th>
                    <th>ngày kết thúc</th>
                    <th>Ngày tạo</th>
                    <th>Ngày cập nhật</th>
                    <th></th>

                </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                @foreach (var item in Model)
                {
                    i = i + 1;
                <tr>
                    <td>@i</td>
                    <td>@item.Titel</td>
                    <td>@item.Note</td>
                    <td>@item.StartDate.Value.ToString("dd/MM/yyyy")</td>
                    <td>@item.EndDate.Value.ToString("dd/MM/yyyy")</td>
                    <td>@(item.CreatedDate.Value.ToString("dd/MM/yyyy"))</td>
                    <td>@(item.ModifiedDate.Value.ToString("dd/MM/yyyy"))</td>
                    <td>
                        <a href="@Url.Action("Edit", "GradingPlan", new { Id = item.Id})">Chỉnh sửa</a>
                        |
                        <a href="@Url.Action("Delete", "GradingPlan", new { Id = item.Id})">Xóa</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>