EvaluationSystem/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Mã")]
        [Required(ErrorMessage = "Vui lòng điền mã")]
        public string Code { get; set; }
        [Required(ErrorMessage = "Vui lòng điền tên")]
        [Display(Name = "Tên")]
        public string Name { get; set; }
        public string Group { get; set; }
        public int? OrderNo { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }

    }
}

EvaluationSystem/Controllers/CategoryController.cs
using EvaluationSystem.Data.Entities;
using EvaluationSystem.Data.Interfaces;
using EvaluationSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Controllers
{
    public class CategoryController : Controller
    {
        ICategoryRepository _categoryRepository;
        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        // GET: Category
        public ActionResult IndexSemester()
        {
            ViewBag.Group = "hocky";
            return View();
        }
        public ActionResult IndexCourse()
        {
            ViewBag.Group = "khoahoc";
            return View();
        }
        public ActionResult IndexGrid(string group)
        {
            var models = _categoryRepository
                .GetAll()
                .Where(x => x.Group == group)
                .AsNoTracking()
                .OrderByDescending(x => x.CreatedDate)
                .Select(x => new CategoryViewModel
                {
                    Id = x.Id,
                    Code = x.Code,
                    Name = x.Name,
                    Group = x.Group,
                    OrderNo = x.OrderNo,
                    CreatedDate = x.CreatedDate,
                    ModifiedDate = x.ModifiedDate
                });

            return PartialView("_IndexGrid", models);
        }
            public ActionResult Create()
        {
            CategoryViewModel model = new CategoryViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(CategoryViewModel model)
        {
            Category category = new Category();
            category.Name = model.Name;
            category.Code = model.Code;
            category.Group = model.Group;
            category.OrderNo = model.OrderNo;
            category.CreatedDate = DateTime.Now;
            category.IsDeleted = false;
            _categoryRepository.Add(category);
            if (category.Id > 0)
            {
                if (category.Group == "Hocky")
                {
                    return RedirectToAction("IndexSemester");
                }
                return RedirectToAction("IndexCourse");
            }
            return View(model);
        }
        public ActionResult Edit(int Id)
        {
            var category = _categoryRepository.GetById(Id);
            CategoryViewModel model = new CategoryViewModel();
            if (category != null)
            {
                model.Name = category.Name;
                model.Code = category.Code;
                return View(model);
            }
            return RedirectToAction("IndexSemester");
        }
        [HttpPost]
        public ActionResult Edit(CategoryViewModel model)
        {
            
            var category = _categoryRepository.GetById(model.Id);
            if (category != null)
            {
                category.Name = model.Name;
                category.Code = model.Code;
                category.ModifiedDate = DateTime.Now;
                _categoryRepository.Update(category);
                return RedirectToAction("IndexSemester");
            }
            return View(model);
        }
        public ActionResult Delete(int Id)
        {
            var category = _categoryRepository.GetById(Id);
            if (category != null)
            {
                _categoryRepository.DeleteRs(Id);

                return RedirectToAction("IndexSemester");
            }
            return RedirectToAction("IndexSemester");
        }
    }
}

EvaluationSystem/Views/Category/CreateCourse.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

<!-- Basic Layout & Basic with Icons -->
<div class="row">
    <!-- Basic Layout -->
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Khóa học</h5>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("CreateCourse", "Category", FormMethod.Post))
                {
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Tên khóa</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                            @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Số thứ tự khóa</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.OrderNo, new { @class = "form-control", style = "", type = "number" })
                            @Html.ValidationMessageFor(x => x.OrderNo, null, new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

EvaluationSystem/Views/Category/CreateSemester.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

<!-- Basic Layout & Basic with Icons -->
<div class="row">
    <!-- Basic Layout -->
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Trang thêm học kỳ</h5>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("CreateSemester", "Category", FormMethod.Post))
                {
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Tên học kỳ</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                            @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Mã học kỳ</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Code, new { @class = "form-control", style = "" })
                            @Html.ValidationMessageFor(x => x.Code, null, new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-sm-2 col-form-label">Số thứ tự học kỳ</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.OrderNo, new { @class = "form-control", style = "", type = "number" })
                            @Html.ValidationMessageFor(x => x.OrderNo, null, new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

EvaluationSystem/Views/Category/EditCourse.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

<!-- Basic Layout & Basic with Icons -->
<div class="row">
    <!-- Basic Layout -->
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Trang cập nhật khóa</h5>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EditCourse", "Category", FormMethod.Post))
                {
                    <div class="row mb-3">
                        @Html.LabelFor(x => x.Name, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                        </div>
                    </div>
                    <div class="row mb-3">
                        @Html.LabelFor(x => x.Code, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Code, new { @class = "form-control", style = "" })
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- / Content -->
<!-- Footer -->

EvaluationSystem/Views/Category/EditSemester.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Content -->

<h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Forms/</span> Horizontal Layouts</h4>

<!-- Basic Layout & Basic with Icons -->
<div class="row">
    <!-- Basic Layout -->
    <div class="col-xxl">
        <div class="card mb-4">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="mb-0">Trang cập nhật học kỳ</h5>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("EditSemester", "Category", FormMethod.Post))
                {
                    <div class="row mb-3">
                        @Html.LabelFor(x => x.Name, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                        </div>
                    </div>
                    <div class="row mb-3">
                        @Html.LabelFor(x => x.Code, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-10">
                            @Html.TextBoxFor(x => x.Code, new { @class = "form-control", style = ""})
                        </div>
                    </div>
                    <div class="row justify-content-end">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<!-- / Content -->
<!-- Footer -->

EvaluationSystem/Views/Category/IndexCourse.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var group = ViewBag.Group as string;
}

<h4>Danh sách khóa học</h4>
<div class="card mb-3">
    @*<div class="card-body">
            <div class="row mb-2">
                <div class="col-md-2 px-1">
                    @Html.TextBox("fullName", "", new { @class = "form-control", @placeholder = "Tên sinh viên" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.TextBox("code", "", new { @class = "form-control", @placeholder = "Mã số sinh viên" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("classId", Model.ClassList, new { @class = "form-control" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("majorsId", Model.MajorsList, new { @class = "form-control" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("facultyId", Model.FacultyList, new { @class = "form-control" })
                </div>
            </div>
        </div>*@
    <div style="margin-bottom: 20px; margin-left: 20px">
        <button type="button" class="btn btn-sm btn-primary"
                onclick="OpenPopup('@Url.Action("Create", "Category", new{ IsPopup = true })', 'Thêm khóa học','s', 500)">
            <i class="bx bx-plus-circle"></i>
            Thêm khóa học
        </button>
        @*<button type="button" class="btn btn-sm btn-secondary">Secondary</button>*@
    </div>
</div>
<div class="card mb-3">
    <div class="table-responsive text-nowrap" id="grid-container">
        @Html.AjaxGrid(Url.Action("IndexGrid", new { group = group }))
    </div>
</div>


@section ScriptBottom {
    <script type="text/javascript">
        $(document).ready(function () {
            new MvcGrid(document.querySelector('.mvc-grid'));
        });

        $(document).ready(function () {
            var group = '@group';
            $.ajax({
                url: '@Url.Action("IndexGrid", new { group = group })',
                type: 'GET',
                success: function (data) {
                    $('#grid-container').html(data);
                }
            });
        });

        function ClosePopupAndReloadGrid() {
            ClosePopup();
            ReloadGrid();
        }

        function DeleteItem(Id) {
            if (confirm('Bạn có chắc muốn xóa sinh viên?')) {
                $.ajax({
                    url: '@Url.Action("Delete")',
                    type: "POST",
                    data: { Id: Id },
                    success: function (res) {
                        alert(res.message, res.type)
                        ReloadGrid();
                    }
                });
            }
        }

        function ReloadGrid() {
            var grid = new MvcGrid(document.querySelector('.mvc-grid'));
            grid.reload();
        }

    </script>
}

EvaluationSystem/Views/Category/IndexSemester.cshtml
@model CategoryViewModel
@using EvaluationSystem.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var group = ViewBag.Group as string;
}

<h4>Danh sách khóa học</h4>
<div class="card mb-3">
    @*<div class="card-body">
            <div class="row mb-2">
                <div class="col-md-2 px-1">
                    @Html.TextBox("fullName", "", new { @class = "form-control", @placeholder = "Tên sinh viên" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.TextBox("code", "", new { @class = "form-control", @placeholder = "Mã số sinh viên" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("classId", Model.ClassList, new { @class = "form-control" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("majorsId", Model.MajorsList, new { @class = "form-control" })
                </div>
                <div class="col-md-2 px-1">
                    @Html.DropDownList("facultyId", Model.FacultyList, new { @class = "form-control" })
                </div>
            </div>
        </div>*@
    <div style="margin-bottom: 20px; margin-left: 20px">
        <button type="button" class="btn btn-sm btn-primary"
                onclick="OpenPopup('@Url.Action("Create", "Category", new{ IsPopup = true })', 'Thêm học kỳ','s', 500)">
            <i class="bx bx-plus-circle"></i>
            Thêm học kì
        </button>
        @*<button type="button" class="btn btn-sm btn-secondary">Secondary</button>*@
    </div>
</div>
<div class="card mb-3">
    <div class="table-responsive text-nowrap" id="grid-container">
        @Html.AjaxGrid(Url.Action("IndexGrid", new { group = group }))
    </div>
</div>


@section ScriptBottom {
    <script type="text/javascript">
        $(document).ready(function () {
            new MvcGrid(document.querySelector('.mvc-grid'));
        });

        $(document).ready(function () {
            var group = '@group';
            $.ajax({
                url: '@Url.Action("IndexGrid", new { group = group })',
                type: 'GET',
                success: function (data) {
                    $('#grid-container').html(data);
                }
            });
        });

        function ClosePopupAndReloadGrid() {
            ClosePopup();
            ReloadGrid();
        }

        function DeleteItem(Id) {
            if (confirm('Bạn có chắc muốn xóa sinh viên?')) {
                $.ajax({
                    url: '@Url.Action("Delete")',
                    type: "POST",
                    data: { Id: Id },
                    success: function (res) {
                        alert(res.message, res.type)
                        ReloadGrid();
                    }
                });
            }
        }

        function ReloadGrid() {
            var grid = new MvcGrid(document.querySelector('.mvc-grid'));
            grid.reload();
        }

    </script>
}

EvaluationSystem/Views/Category/_IndexGrid.cshtml
@model IQueryable<CategoryViewModel>
@using EvaluationSystem.Models

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Name);
        columns.Add(model => model.Code);
        columns.Add(model => model.CreatedDate).Formatted("{0: dd/MM/yyyy }");
        columns.Add().Titled("Hoạt động").Encoded(false).RenderedAs(x => GridColumnAction(x.Id));
    })
    .Empty("No data found")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String>
            {{ 10, "10" },{ 15, "15" }, { 20, "20" }, { 50, "50" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 5;
        pager.RowsPerPage = 10;
    })
    .Sortable()
)

@helper GridColumnAction(int Id)
{
    <a href="javascript:void(0)" class="text-warning" onclick="OpenPopup('@Url.Action("Edit", "Category", new{ IsPopup = true,  Id = Id})', 'Cập nhật','s', 500)">
        <i class="bx bx-edit-alt me-1" style="font-size: 25px"></i>
    </a>
    <a href="javascript:void(0)" class="text-danger" onclick="DeleteItem(@Id)">
        <i class="bx bx-trash me-1" style="font-size: 25px"></i>
    </a>
}