EvaluationSystem/Controllers/ClassController.cs
using EvaluationSystem.Data.Entities;
using EvaluationSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EvaluationSystem.Data.Repositories;
using EvaluationSystem.Data.Interfaces;
using System.Data.Entity;
using Newtonsoft.Json;

namespace EvaluationSystem.Controllers
{
    public class ClassController : Controller
    {
        IClassRepository _classRepository;
        IMajorsRepository _majorsRepository;
        IStudentRepository _studentRepository;
        IFacultyRepository _facultyRepository;
        public ClassController( IFacultyRepository facultyRepository, IClassRepository classRepository, IMajorsRepository majorsRepository, IStudentRepository studentRepository)
        {
            _classRepository = classRepository;
            _majorsRepository = majorsRepository;
            _studentRepository = studentRepository;
            _facultyRepository = facultyRepository;
        }
        public ActionResult Index()
        {
            var model = new ClassViewModel();
            var majorsGroupList = _majorsRepository.GetAll().OrderByDescending(x => x.CreatedDate);
            model.MajorsList = GetSelectList(majorsGroupList, "Id", "Name", "", "--Ngành--");
            var facultyGroupList = _facultyRepository.GetAll().OrderByDescending(x => x.CreatedDate);
            model.FacultyList = GetSelectList(facultyGroupList, "Id", "Name", "", "--Khoa--");
            return View(model);
        }
        public PartialViewResult IndexGrid(string name, string code, int? majorsId, int? facultyId)
        {
            majorsId = majorsId ?? 0;
            name = (name ?? "").Trim().ToLower();
            code = (code ?? "").Trim().ToLower();
            facultyId = facultyId ?? 0;

            var _class = _classRepository.ListAll().Where(x =>
                (majorsId == 0 || x.MajorsId == majorsId)
                && (facultyId == 0 || x.Majors.FacultyId == facultyId)
                && (name == "" || x.Name.Contains(name))
                && (code == "" || x.Code.Contains(code))
                );
            var models = _class
                .Include(x=>x.Majors.Faculty)
                .AsNoTracking()
                .OrderByDescending(x=>x.CreatedDate)
                .Select(x => new ClassViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Code = x.Code,
                    CreatedDate = x.CreatedDate,
                    MajorsCode = x.Majors.Code,
                    MajorsName = x.Majors.Name,
                });

            return PartialView("_IndexGrid", models);
        }
        protected SelectList GetSelectList(IQueryable<object> list, string value, string text, object selected = null, string NullOrNameEmpty = null)
        {
            var selectList = new SelectList(list, value, text).ToList();
            if (NullOrNameEmpty != null)
            {
                SelectListItem itemEmpty = new SelectListItem();
                itemEmpty.Text = NullOrNameEmpty;
                itemEmpty.Value = null;
                selectList.Insert(0, itemEmpty);
            }
            return new SelectList(selectList, "Value", "Text", selected);
        }

        // GET: Class/Details/5
        public ActionResult Detail(int Id)
        {
            var _class = _classRepository.GetInfoById(Id);
            var model = new ClassViewModel();
            if (_class != null)
            {
                model.Id = _class.Id;
                model.Name = _class.Name;
                model.Code = _class.Code;
                model.CreatedDate = _class.CreatedDate;
                model.MajorsId = _class.MajorsId;
                model.MajorsName = _class.Majors?.Name;
                model.MajorsCode = _class.Majors?.Code;
                model.FacultyId = _class.Majors?.FacultyId;
                model.FacultyCode = _class.Majors?.Faculty?.Code;
                model.FacultyName = _class.Majors?.Faculty?.Name;
                model.CountStudent = _studentRepository.CountStudent(Id);

                return View(model);
            }
            return RedirectToAction("Index");
        }
        public PartialViewResult DetailGrid(int classId)
        {
            var models = _studentRepository.GetStudentbyClassId(classId)
                .AsNoTracking()
                .OrderByDescending(x => x.CreatedDate)
                .Select(x => new StudentViewModel
                {
                    Id = x.Id,
                    FullName = x.FullName,
                    Code = x.Code,
                    BirthDate = x.BirthDate,
                    ClassName = x.Class.Name,
                    CreatedDate = x.CreatedDate,
                    ModifiedDate = x.ModifiedDate
                });

            return PartialView("_DetailGrid", models);
        }

        // GET: Class/Create
        public ActionResult Create()
        {
            ClassViewModel model = new ClassViewModel();
            GetData(model);
            return View(model);
        }
        public void GetData(ClassViewModel model)
        {
            var majorsListDb = _majorsRepository.GetAll();
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem()
            {
                Text = "-- Chọn --",
                Value = null,
            });
            foreach (var item in majorsListDb)
            {
                /*var selectListItem = new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                };*/
                var selectListItem = new SelectListItem();
                selectListItem.Text = item.Name;
                selectListItem.Value = item.Id.ToString();
                list.Add(selectListItem);
            }
            model.MajorsList = new SelectList(list, "Value", "Text");
        }
        // POST: Class/Create
        [HttpPost]
        public ActionResult Create(ClassViewModel model)
        {
            if (ModelState.IsValid)
            {
                Class _class = new Class();
                _class.Code = model.Code;
                _class.Name = model.Name;
                _class.CreatedDate = DateTime.Now;
                _class.MajorsId = model.MajorsId;
                _classRepository.Add(_class);
                if (_class.Id>0)
                {
                    if (Request["IsPopup"] != null)
                    {
                        return RedirectToAction("_ClosePopup", "Home",
                            new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                    }
                    return RedirectToAction("Index");
                }
            }
            GetData(model);
            return View(model);
        }

        // GET: Class/Edit/5
        public ActionResult Edit(int id)
        {
            var _class = _classRepository.GetById(id);
            ClassViewModel model = new ClassViewModel();
            if (_class != null)
            {
                model.Id = _class.Id;
                model.CreatedDate = _class.CreatedDate;
                model.Code = _class.Code;
                model.Name = _class.Name;
                model.MajorsId = _class.MajorsId;
                GetData(model);
                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }
 
        }

        // POST: Class/Edit/5
        [HttpPost]
        public ActionResult Edit(ClassViewModel model)
        {
            if (ModelState.IsValid)
            {
                var _class = _classRepository.GetById(model.Id);
                if (_class != null)
                {
                    _class.Name = model.Name;
                    _class.Code = model.Code;
                    _class.MajorsId = model.MajorsId;
                    _class.ModifiedDate = DateTime.Now;
                    _classRepository.Update(_class);
                    return RedirectToAction("_ClosePopup", "Home",
                        new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                }
            }
            GetData(model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {

            var _class = _classRepository.GetById(id);
            if (_class != null)
            {
                _classRepository.Delete(_class);

                return Json(new { message = "Xóa thành công", type = "success" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { message = "Xóa không thành công", type = "error" }, JsonRequestBehavior.AllowGet);
        }
        
    }
}

EvaluationSystem/Controllers/ErrorPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Controllers
{
    public class ErrorPageController : Controller
    {
        // GET: ErrorPage
        public ActionResult Index()
        {
            return View();
        }
    }
}

EvaluationSystem/Controllers/MajorsController.cs
using EvaluationSystem.Data.Entities;
using EvaluationSystem.Data.Interfaces;
using EvaluationSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Controllers
{
    public class MajorsController : Controller
    {
        IMajorsRepository _majorsRepository;
        IFacultyRepository _facultyRepository;
        IClassRepository _classRepository;
        IStudentRepository _studentRepository;
        public MajorsController(IMajorsRepository majorsRepository
            , IFacultyRepository facultyRepository
            , IStudentRepository studentRepository
            , IClassRepository classRepository)
        {
            _majorsRepository = majorsRepository;
            _facultyRepository = facultyRepository;
            _classRepository = classRepository;
            _studentRepository = studentRepository;
        }
        // GET: Majors
        public ActionResult Index()
        {
            var model = new MajorsViewModel();
            GetData(model);
            return View(model);
        }
        public PartialViewResult IndexGrid(string name, string code, int? facultyId)
        {
            name = (name ?? "").Trim().ToLower();
            code = (code ?? "").Trim().ToLower();
            facultyId = facultyId ?? 0;

            var models = _majorsRepository.GetAll()
                .Where(x =>
                (facultyId == 0 || x.FacultyId == facultyId)
                && (name == "" || x.Name.Contains(name))
                && (code == "" || x.Code.Contains(code))
                && (x.IsDeleted != true)
                )
                .Include(x => x.Faculty)
                .AsNoTracking()
                .OrderByDescending(x => x.CreatedDate)
                .Select(x => new MajorsViewModel
                {
                Id = x.Id,
                Name = x.Name,
                Code = x.Code,
                CreatedDate = x.CreatedDate,
                ModifiedDate = x.ModifiedDate,
                FacultyName = x.Faculty.Name,
            });

            return PartialView("_IndexGrid",models);
        }
        public ActionResult Details(int Id)
        {
            var majors = _majorsRepository.GetInfoById(Id);
            var model = new MajorsViewModel();
            if (majors != null)
            {
                model.Id = majors.Id;
                model.Name = majors.Name;
                model.Code = majors.Code;
                model.CreatedDate = majors.CreatedDate;
                model.FacultyId = majors.FacultyId;
                model.FacultyName = majors.Faculty?.Name;
                model.FacultyCode = majors.Faculty?.Code;

                return View(model);
            }
            return RedirectToAction("Index");
        }
        public ActionResult DetailGrid(int majorsId)
        {
            var models = _classRepository.GetClassByMajors(majorsId)
                .AsNoTracking()
                .OrderByDescending(x => x.CreatedDate)
                .Select(x => new ClassViewModel
                {
                    Id = x.Id,
                    Code = x.Code,
                    Name = x.Name,
                    CreatedDate = x.CreatedDate,
                });
            return PartialView("_DetailGrid", models);
        }
        public void GetData(MajorsViewModel model)
        {
            var facultyListDb = _facultyRepository.GetAll().OrderByDescending(x => x.CreatedDate);
            var list = new List<SelectListItem>();
            list.Add(new SelectListItem()
            {
                Text = "-- Chọn khoa --",
                Value = null,
            });
            foreach (var item in facultyListDb)
            {
                var selectListItem = new SelectListItem();
                selectListItem.Text = item.Name;
                selectListItem.Value = item.Id.ToString();
                list.Add(selectListItem);
            }
            model.FacultyList = new SelectList(list, "Value", "Text");
        }
        public ActionResult Create()
        {
            MajorsViewModel model = new MajorsViewModel();
            ViewBag.Title = "Trang thêm ngành";
            GetData(model);
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(MajorsViewModel models)
        {
            if (ModelState.IsValid)
            {
                Majors majors = new Majors();
                majors.Name = models.Name;
                majors.Code = models.Code;
                majors.CreatedDate = DateTime.Now;
                majors.FacultyId = models.FacultyId;
                _majorsRepository.Add(majors);
                if (majors.Id > 0)
                {
                    return RedirectToAction("_ClosePopup", "Home",
                        new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                }
            }
            GetData(models);
            return View(models);
        }
        public ActionResult Edit(int Id)
        {
            var majors = _majorsRepository.GetById(Id);
            MajorsViewModel model = new MajorsViewModel();
            if (majors != null)
            {
                model.Id = majors.Id;
                model.Code = majors.Code;
                model.Name = majors.Name;
                model.FacultyId = majors.FacultyId;
                GetData(model);
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(MajorsViewModel model)
        {
            if (ModelState.IsValid)
            {
                var majors = _majorsRepository.GetById(model.Id);
                if (majors != null)
                {
                    majors.Name = model.Name;
                    majors.Code = model.Code;
                    majors.ModifiedDate = DateTime.Now;
                    majors.FacultyId = model.FacultyId;
                    _majorsRepository.Update(majors);
                    return RedirectToAction("_ClosePopup", "Home",
                        new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                }
                return RedirectToAction("Index");
            }
            GetData(model);
            return View(model);
        }
        public ActionResult Delete(int Id)
        {
            var majors = _majorsRepository.GetById(Id);
            if (majors != null)
            {
                _majorsRepository.Delete(Id);

                return Json(new { message = "Xóa thành công", type = "success" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { message = "Xóa không thành công", type = "error" }, JsonRequestBehavior.AllowGet);
        }
    }
}

EvaluationSystem/Views/Shared/_Sidebar.cshtml
@{ 
    string path = HttpContext.Current.Request.Url.AbsolutePath;

}

<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="/" class="app-brand-link">
            <span class="app-brand-logo demo">
                <svg width="25"
                     viewBox="0 0 25 42"
                     version="1.1"
                     xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink">
                    <defs>
                        <path d="M13.7918663,0.358365126 L3.39788168,7.44174259 C0.566865006,9.69408886 -0.379795268,12.4788597 0.557900856,15.7960551 C0.68998853,16.2305145 1.09562888,17.7872135 3.12357076,19.2293357 C3.8146334,19.7207684 5.32369333,20.3834223 7.65075054,21.2172976 L7.59773219,21.2525164 L2.63468769,24.5493413 C0.445452254,26.3002124 0.0884951797,28.5083815 1.56381646,31.1738486 C2.83770406,32.8170431 5.20850219,33.2640127 7.09180128,32.5391577 C8.347334,32.0559211 11.4559176,30.0011079 16.4175519,26.3747182 C18.0338572,24.4997857 18.6973423,22.4544883 18.4080071,20.2388261 C17.963753,17.5346866 16.1776345,15.5799961 13.0496516,14.3747546 L10.9194936,13.4715819 L18.6192054,7.984237 L13.7918663,0.358365126 Z"
                              id="path-1"></path>
                        <path d="M5.47320593,6.00457225 C4.05321814,8.216144 4.36334763,10.0722806 6.40359441,11.5729822 C8.61520715,12.571656 10.0999176,13.2171421 10.8577257,13.5094407 L15.5088241,14.433041 L18.6192054,7.984237 C15.5364148,3.11535317 13.9273018,0.573395879 13.7918663,0.358365126 C13.5790555,0.511491653 10.8061687,2.3935607 5.47320593,6.00457225 Z"
                              id="path-3"></path>
                        <path d="M7.50063644,21.2294429 L12.3234468,23.3159332 C14.1688022,24.7579751 14.397098,26.4880487 13.008334,28.506154 C11.6195701,30.5242593 10.3099883,31.790241 9.07958868,32.3040991 C5.78142938,33.4346997 4.13234973,34 4.13234973,34 C4.13234973,34 2.75489982,33.0538207 2.37032616e-14,31.1614621 C-0.55822714,27.8186216 -0.55822714,26.0572515 -4.05231404e-15,25.8773518 C0.83734071,25.6075023 2.77988457,22.8248993 3.3049379,22.52991 C3.65497346,22.3332504 5.05353963,21.8997614 7.50063644,21.2294429 Z"
                              id="path-4"></path>
                        <path d="M20.6,7.13333333 L25.6,13.8 C26.2627417,14.6836556 26.0836556,15.9372583 25.2,16.6 C24.8538077,16.8596443 24.4327404,17 24,17 L14,17 C12.8954305,17 12,16.1045695 12,15 C12,14.5672596 12.1403557,14.1461923 12.4,13.8 L17.4,7.13333333 C18.0627417,6.24967773 19.3163444,6.07059163 20.2,6.73333333 C20.3516113,6.84704183 20.4862915,6.981722 20.6,7.13333333 Z"
                              id="path-5"></path>
                    </defs>
                    <g id="g-app-brand" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Brand-Logo" transform="translate(-27.000000, -15.000000)">
                            <g id="Icon" transform="translate(27.000000, 15.000000)">
                                <g id="Mask" transform="translate(0.000000, 8.000000)">
                                    <mask id="mask-2" fill="white">
                                        <use xlink:href="#path-1"></use>
                                    </mask>
                                    <use fill="#696cff" xlink:href="#path-1"></use>
                                    <g id="Path-3" mask="url(#mask-2)">
                                        <use fill="#696cff" xlink:href="#path-3"></use>
                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-3"></use>
                                    </g>
                                    <g id="Path-4" mask="url(#mask-2)">
                                        <use fill="#696cff" xlink:href="#path-4"></use>
                                        <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-4"></use>
                                    </g>
                                </g>
                                <g id="Triangle"
                                   transform="translate(19.000000, 11.000000) rotate(-300.000000) translate(-19.000000, -11.000000) ">
                                    <use fill="#696cff" xlink:href="#path-5"></use>
                                    <use fill-opacity="0.2" fill="#FFFFFF" xlink:href="#path-5"></use>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
            </span>
            <span class="app-brand-text demo menu-text fw-bolder ms-2">administration</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item @( "/" == path
            ? "active" :"")">
            <a href="/" class="menu-link">
                <i class="menu-icon tf-icons bx bxs-home"></i>
                <div data-i18n="Analytics">Trang chủ</div>
            </a>
        </li>

        <!-- Layouts -->
        <li class="menu-item @(
            Url.Action("Create","Student") == path
            || Url.Action("Index","Student") == path
            || Url.Action("Details","Student") == path
            ? "active open"
            :"")">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-group"></i>
                <div data-i18n="Layouts">Sinh viên</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Student") == path ? "active" :"")">
                    <a href="@Url.Action("Create","Student")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item @(Url.Action("Index","Student") == path || Url.Action("Details","Student") == path ? "active" :"")">
                    <a href="@Url.Action("Index","Student")" class="menu-link">
                        <div data-i18n="Without navbar">Danh sách</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item @(
            Url.Action("Create","Class") == path
            || Url.Action("Index","Class") == path
            || Url.Action("Details","Class") == path
            ? "active open"
            :"")">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxl-microsoft-teams"></i>
                <div data-i18n="Layouts">Lớp</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Class") == path ? "active" :"")" >
                    <a href="@Url.Action("Create","Class")" class="menu-link">
                        <div data-i18n="Without menu">Thêm lớp</div>
                    </a>
                </li>*@
                <li class="menu-item @(Url.Action("Index","Class") == path || Url.Action("Details","Class") == path ? "active" :"")">
                    <a href="@Url.Action("Index","Class")" class="menu-link">
                        <div data-i18n="Without navbar">Danh sách</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item @(
            Url.Action("Create","Majors") == path
            || Url.Action("Index","Majors") == path
            || Url.Action("Details","Majors") == path
            ? "active open"
            :"")">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-layer"></i>
                <div data-i18n="Layouts">Ngành</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Majors") == path ? "active" : "")">
                    <a href="@Url.Action("Create","Majors")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item @(Url.Action("Index","Majors") == path || Url.Action("Details","Majors") == path ? "active" : "")">
                    <a href="@Url.Action("Index","Majors")" class="menu-link">
                        <div data-i18n="Without navbar">Danh sách</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item @(
            Url.Action("Create","Faculty") == path
            || Url.Action("Index","Faculty") == path
            || Url.Action("Details","Faculty") == path
            ? "active open"
            :"")">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-git-branch"></i>
                <div data-i18n="Layouts">Khoa</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Faculty") == path ? "active" : "")">
                    <a href="@Url.Action("Create","Faculty")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item @(Url.Action("Index","Faculty") == path || Url.Action("Details","Faculty") == path ? "active" : "")">
                    <a href="@Url.Action("Index","Faculty")" class="menu-link">
                        <div data-i18n="Without navbar">Danh sách</div>
                    </a>
                </li>
            </ul>
        </li>
        @*<li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-pencil"></i>
                <div data-i18n="Layouts">Kế hoạch chấm điểm</div>
            </a>

            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="@Url.Action("Create","GradingPlan")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="@Url.Action("Index","GradingPlan")" class="menu-link">
                        <div data-i18n="Without navbar">Danh sách</div>
                    </a>
                </li>
            </ul>
        </li>*@

        <li class="menu-item ">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-collection"></i>
                <div data-i18n="Layouts">Học kỳ</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Faculty") == path ? "active" : "")">
                    <a href="@Url.Action("Create","Faculty")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item">
                    <a href="@Url.Action("Index","ErrorPage")" class="menu-link">
                        <div data-i18n="Without navbar">(Coming Soon)</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item ">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-food-menu"></i>
                <div data-i18n="Layouts">Khóa học</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Faculty") == path ? "active" : "")">
                    <a href="@Url.Action("Create","Faculty")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item">
                    <a href="@Url.Action("Index","ErrorPage")" class="menu-link">
                        <div data-i18n="Without navbar">(Coming Soon)</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item ">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bxs-pencil"></i>
                <div data-i18n="Layouts">Kế hoạch chấm điểm</div>
            </a>

            <ul class="menu-sub">
                @*<li class="menu-item @(Url.Action("Create","Faculty") == path ? "active" : "")">
                    <a href="@Url.Action("Create","Faculty")" class="menu-link">
                        <div data-i18n="Without menu">Thêm mới</div>
                    </a>
                </li>*@
                <li class="menu-item">
                    <a href="@Url.Action("Index","ErrorPage")" class="menu-link">
                        <div data-i18n="Without navbar">(Coming Soon)</div>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</aside>