EvaluationSystem/Models/FacultyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EvaluationSystem.Models
{
    public class FacultyViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Chưa điền tên khoa")]
        [Display(Name = "Tên khoa")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Chưa điền mã khoa")]
        [Display(Name = "Mã khoa")]
        public string Code { get; set; }
        [Display(Name = "Ngày tạo")]
        public DateTime? CreatedDate { get; set; }
        [Display(Name = "Ngày cập nhật")]
        public DateTime? ModifiedDate { get; set; }
        public bool? IsDeleted { get; set; }
        public double? FacultySize { get; set; }

        public List<StudentViewModel> StudentsList { get; set; }


    }
}

EvaluationSystem/Controllers/FacultyController.cs
using EvaluationSystem.Data;
using EvaluationSystem.Data.Entities;
using EvaluationSystem.Data.Interfaces;
using EvaluationSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;


namespace EvaluationSystem.Controllers
{
    public class FacultyController : Controller
    {
        IFacultyRepository _facultyRepository;
        public FacultyController(IFacultyRepository facultyRepository)
        {
            _facultyRepository = facultyRepository;
            
        }
        // GET: Faculty
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult IndexGrid(string name, string code)
        {
            name = (name ?? "").Trim().ToLower();
            code = (code ?? "").Trim().ToLower();
            var models = _facultyRepository.GetAll().Where(x =>
                (name =="" || x.Name.Contains(name))
                && (code == "" || x.Code.Contains(code)))
                .AsNoTracking()
                .OrderBy(x => x.CreatedDate)
                .Select(x => new FacultyViewModel
                {
                    Name = x.Name,
                    Code = x.Code,
                    CreatedDate = x.CreatedDate,
                    ModifiedDate = x.ModifiedDate,
                    Id = x.Id
                });
            return PartialView("_IndexGrid", models);
        }
        public ActionResult Create()
        {

            FacultyViewModel model = new FacultyViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(FacultyViewModel models)
        {
            if (ModelState.IsValid)
            {
                Faculty faculty = new Faculty();
                faculty.Name = models.Name;
                faculty.Code = models.Code;
                faculty.CreatedDate = DateTime.Now;
                _facultyRepository.Add(faculty);
                if (Request["IsPopup"] != null)
                {
                    return RedirectToAction("_ClosePopup", "Home",
                        new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                }
                return RedirectToAction("Index");
            }
            return View(models);
        }
        public ActionResult Edit(int Id)
        {
            var faculty = _facultyRepository.GetById(Id);
            if (faculty != null)
            {
                FacultyViewModel model = new FacultyViewModel();    
                model.Id = faculty.Id;
                model.CreatedDate = faculty.CreatedDate;
                model.Code = faculty.Code;
                model.Name = faculty.Name;
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(FacultyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var faculty = _facultyRepository.GetById(model.Id);
                if (faculty != null)
                {
                    faculty.Name = model.Name;
                    faculty.Code = model.Code;
                    faculty.ModifiedDate = DateTime.Now;
                    _facultyRepository.Update(faculty);

                    return RedirectToAction("_ClosePopup", "Home",
                        new { area = "", FunctionCallback = "ClosePopupAndReloadGrid" });
                }
            }
            return View(model);
        }
        public ActionResult Delete(int id)
        {
            var faculty = _facultyRepository.GetById(id);
            if (faculty != null)
            {
                _facultyRepository.DeleteRs(faculty.Id);

                return Json(new { message = "Xóa thành công", type = "success" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { message = "Xóa không thành công", type = "error" }, JsonRequestBehavior.AllowGet);
        }
    }
}

EvaluationSystem/Views/Faculty/Create.cshtml
@model FacultyViewModel
@using EvaluationSystem.Models;
@{
    var isPop = Request["IsPopup"];
    Layout = "~/Views/Shared/" + (isPop == null ? "_Layout.cshtml" : "_PopupLayout.cshtml");

}

<div class="card-header d-flex align-items-center justify-content-between">
    <h5 class="mb-0">Thêm khoa</h5>
</div>
<div class="card-body">
    @using (Html.BeginForm("Create", "Faculty", FormMethod.Post))
    {
        <input name="IsPopup" type="hidden" value="@Request["IsPopup"]" />
        <div class="row mb-3">
            @Html.LabelFor(x => x.Name, new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-3">
            @Html.LabelFor(x => x.Code, new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Code, new { @class = "form-control", style = "" })
                @Html.ValidationMessageFor(x => x.Code, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Lưu</button>
            </div>
        </div>
    }
</div>

EvaluationSystem/Views/Faculty/Edit.cshtml
@model FacultyViewModel
@using EvaluationSystem.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var isPop = Request["IsPopup"];
    Layout = "~/Views/Shared/" + (isPop == null ? "_Layout.cshtml" : "_PopupLayout.cshtml");

}


<div class="card-header d-flex align-items-center justify-content-between">
    <h5 class="mb-0">Chỉnh sửa khoa</h5>
</div>
<div class="card-body">
    @using (Html.BeginForm("Edit", "Faculty", FormMethod.Post))
    {
        <input name="IsPopup" type="hidden" value="@Request["IsPopup"]" />
        @Html.HiddenFor(x => x.Id)
        <div class="row mb-3">
            @Html.LabelFor(x => x.Name, new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "" })
                @Html.ValidationMessageFor(x => x.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="row mb-3">
            @Html.LabelFor(x => x.Code, new { @class = "col-sm-2 col-form-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Code, new { @class = "form-control", style = "" })
                @Html.ValidationMessageFor(x => x.Code, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Cập nhật</button>
            </div>
        </div>
    }
</div>
<!-- / Content -->
<!-- Footer -->

EvaluationSystem/Views/Faculty/Index.cshtml
@{
    ViewBag.Title = "Index";
    var isPop = Request["IsPopup"];
    Layout = "~/Views/Shared/" + (isPop == null ? "_Layout.cshtml" : "_PopupLayout.cshtml");
}
<h4>Danh sách khoa</h4>
<div class="card mb-3">
    <div class="card-body">
        <div class="row mb-2">
            <div class="col-md-2 px-1">
                @Html.TextBox("name", "", new { @class = "form-control", @placeholder = "Tên khoa" })
            </div>
            <div class="col-md-2 px-1">
                @Html.TextBox("code", "", new { @class = "form-control", @placeholder = "Mã khoa" })
            </div>
        </div>
    </div>
    <div style="margin-bottom: 20px; margin-left: 20px">
        <button type="button" class="btn btn-sm btn-primary"
                onclick="OpenPopup('@Url.Action("Create", "Faculty", new{ IsPopup = true })', 'Thêm khoa','s', 500)">
            <i class="bx bx-plus-circle"></i>
            Thêm khoa
        </button>
        @*<button type="button" class="btn btn-sm btn-secondary">Secondary</button>*@
    </div>
</div>

<div class="card">
    @Html.AjaxGrid(Url.Action("IndexGrid"))
</div>
@section ScriptBottom {
    <script type="text/javascript">
        document.getElementById('name').addEventListener('input', function () {
            search('name', this.value);
        });
        document.getElementById('code').addEventListener('input', function () {
            search('code', this.value);
        });
        $(document).ready(function () {
            new MvcGrid(document.querySelector('.mvc-grid'));
        });

        function ClosePopupAndReloadGrid() {
            ClosePopup();
            ReloadGrid();
        }
        function search(key, value) {
            var grid = new MvcGrid(document.querySelector('.mvc-grid'));
            grid.query.set(key, value);
            grid.reload();
        }


        function DeleteItem(Id) {
            if (confirm('Bạn có chắc muốn xóa?')) {
                $.ajax({
                    url: '@Url.Action("Delete")',
                    type: "POST",
                    data: { Id: Id },
                    success: function (res) {
                        alert(res.message, res.type)
                        ReloadGrid();
                    }
                });
            }
        }

        function ReloadGrid() {
            var grid = new MvcGrid(document.querySelector('.mvc-grid'));
            grid.query.set('name', $('#Name').val());
            grid.query.set('code', $('Code').val());
            grid.reload();
        }
    </script>
}

EvaluationSystem/Views/Faculty/_IndexGrid.cshtml
@model IQueryable<FacultyViewModel>
@using EvaluationSystem.Models

@(Html
    .Grid(Model)
    .Build(columns =>
    {
        columns.Add(model => model.Name);
        columns.Add(model => model.Code);
        columns.Add(model => model.CreatedDate).Formatted("{0:HH:mm dd/MM/yyyy }");
        columns.Add(model => model.ModifiedDate).Formatted("{0:HH:mm dd/MM/yyyy }");
        columns.Add().Titled("Hoạt động").Encoded(false).RenderedAs(x => GridColumnAction(x.Id));
    })
    .Empty("Chưa có khoa")
    .Pageable(pager =>
    {
        pager.PageSizes = new Dictionary<Int32, String>
            {{ 10, "10" },{ 15, "15" }, { 20, "20" }, { 50, "50" } };
        pager.ShowPageSizes = true;
        pager.PagesToDisplay = 5;
        pager.RowsPerPage = 10;
    })
    .Sortable()
)


@helper GridColumnAction(int id)
{
    <a href="javascript:void(0)" class="text-warning" onclick="OpenPopup('@Url.Action("Edit", "Faculty", new{ IsPopup = true,  Id = id})', 'Cập nhật','s', 500)">
        <i class="bx bx-edit-alt me-1" style="font-size: 25px"></i>
    </a>
    <a href="javascript:void(0)" class="text-danger" onclick="DeleteItem(@id)">
        <i class="bx bx-trash me-1" style="font-size: 25px"></i>
    </a>
}